services:
  db:
    image: mysql:8.4
    container_name: myapp_db
    networks:
      - projectex_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=approotpass
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapppass
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    container_name: backend
    networks:
      - projectex_network
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  projectex_network:
    driver: bridge
    
volumes:
  mysql_data:
